[[constraint]]
  name = "cloud.google.com/go"
  version = "0.40.0"

[[constraint]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  version = "0.5.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.16.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/ZB-io/zbio"
  version = "v0.0.6"

[prune]
  go-tests = true
  unused-packages = true
