kind: Pod
apiVersion: v1
metadata:
  name: zbio-example-producer
  labels:
    app: zbio-example-producer
spec:
  containers:
  - name: zbio-example-producer
    image: zbio-example/producer:v1
    imagePullPolicy: Never
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0
