apiVersion: v1
kind: Pod
metadata:
  name: bar
  labels:
    app: bar-lab
spec:
  containers:
  - name: bar
    image: bar:v1
    env:
    - name: FOSS_SERVICE
      value: foo:80
    - name: FOX_SERVICE
      value: foo:81
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - name: bar-port
        containerPort: 8080
