apiVersion: v1
kind: Pod
metadata:
  name: zbio-sample-googlebookapi
  labels:
    app: zbio-sample-googlebookapi
spec:
  containers:
  - name: bookapi
    image: zbio-example/googlebookapi:v1
    ports:
      - containerPort: 9999
    env:
    - name: SERVICE_ADDRESS
      value: zbio-service.zbio:50002
    - name: BROKER_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    imagePullPolicy: Never
    resources:
      requests: {}
      limits: {}
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: googlebookapi
  labels:
    app: zbio-sample-googlebookapi
spec:
  type: LoadBalancer
  selector:
    app: zbio-sample-googlebookapi
  ports:
  - name: tcp
    port: 9999
    targetPort: 9999
