apiVersion: v1
kind: Pod
metadata:
  name: collaborate
  labels:
    app: collaborate
spec:
  containers:
  - name: fetcher
    image: roost-example/fetcher:v1
    env:
    - name: STORAGE_DIR
      value: /app-store
    volumeMounts:
    - mountPath: /app-store
      name: article-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - name: fetcher-port
        containerPort: 8080
    imagePullPolicy: Never
  - name: retriever
    image: roost-example/retriever:v1
    env:
    - name: STORAGE_DIR
      value: /app-store
    volumeMounts:
    - mountPath: /app-store
      name: article-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    # readinessProbe:
    #   exec:
    #     command: 
    #     - "test"
    #     - "-f"
    #     - "/app-store/devio_articles.json"
    imagePullPolicy: Never
  terminationGracePeriodSeconds: 0
  volumes:
  - name: article-storage
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: collaborate
spec:
  type: NodePort
  selector:
    app: collaborate
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30047
