apiVersion: v1
kind: Pod
metadata:
  name: collab-retriever
  labels:
    app: retriever
spec:
  containers:
  - name: retriever
    image: roost-example/retriever:v1
    env:
    - name: FETCH_SERVICE
      value: fetcher:30047
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - name: retriever-port
        containerPort: 8081
    imagePullPolicy: Never
  terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: Service
metadata:
  name: retriever
spec:
  type: NodePort
  selector:
    app: retriever
  ports:
  - name: retriever-port
    port: 30048
    targetPort: 8081
    nodePort: 30048
